---
title: "Conditional Inference for Repeated Measures models"
author: "Livio Finos"
output: 
  html_document:
    toc: yes
    # toc_float: yes
  beamer_presentation: default  
  ioslides_presentation:
    logo: figs/logoUnipd.jpg
  pdf_document:
    keep_tex: yes
    number_sections: yes
    toc: yes
---

# Permutation tests

## (minimal) Bibliography

The Theory:  

- Pesarin (2001) Multivariate Permutation Tests: With Applications in Biostatistics, Wiley, New York  
- Lehmann, E. L., & Romano, J. P. (2006). Testing statistical hypotheses. Springer.  
- An alternative view to the Permutation testing:  Hemerik J, Goeman J. Exact testing with random permutations. Test (Madr). 2018;27(4):811-825. doi: 10.1007/s11749-017-0571-1. Epub 2017 Nov 30. PMID: 30930620; PMCID: PMC6405018.  

## A tutorial (my)

Based on R package `flip`:
 <https://github.com/livioivil/flip> and on CRAN
 
- [html](https://htmlpreview.github.io/?https://github.com/livioivil/inference_basics/blob/master/perm.html)  
- [Rmd](https://github.com/livioivil/inference_basics/blob/master/perm.Rmd)  
- [pdf](https://github.com/livioivil/inference_basics/blob/master/perm.pdf)


Other Packages:  
- permuco <https://cran.r-project.org/web/packages/permuco/index.html>  
- permute <https://cran.r-project.org/web/packages/permute/index.html>


# Permutation Testing with Repeated Measures  

## Random coefficient Analysis / Group-level analysis

Again, using the R `flip` package:
 <https://github.com/livioivil/flip> and on CRAN

- [html](https://htmlpreview.github.io/?https://github.com/livioivil/inference_basics/blob/master/perm_repeated_measures.html)  
- [Rmd](https://github.com/livioivil/inference_basics/blob/master/perm_repeated_measures.Rmd)  
- [pdf](https://github.com/livioivil/inference_basics/blob/master/perm_repeated_measures.pdf)

### (minimal) Bibliography

- Basso \& Finos (2012). Exact Multivariate Permutation Tests for Fixed
Effects in Mixed-Models. *Communications in Statistics - Theory and Methods*, 41: 2991 - 3001.

- Finos \& Basso (2014) Permutation tests for between-unit fixed effects in multivariate
generalized linear mixed models. *Stat Comput* 24, 941–952.



### Why is it cool? you don't estimate the Fisher Information (i.e. the residual variance), an example with paired t-test

```{r}

n=20
y=rnorm(n)

FLIPS=flipscores:::.make_flips(n,1000)
head(FLIPS)
Tstat=FLIPS%*%y
flipscores:::.t2p(Tstat)

MCMC=10000
Y=matrix(rnorm(n*MCMC),n,MCMC)
Tstat=FLIPS%*%Y
p.values=apply(Tstat,2,flipscores:::.t2p)
mean(p.values<.05)


#########
t.test.light <- function(Y,tail=1){
  sd=apply(Y,2,sd,na.rm=TRUE)
  n=nrow(Y)
  ts= colMeans(Y,na.rm=TRUE)/sd*sqrt(n)
  pt(-ts,df = n-1)
}
###########

Y=replicate(MCMC,rnorm(n,sd = exp(1:n)))
Tstat=FLIPS%*%Y
p.values=apply(Tstat,2,flipscores:::.t2p)
p.values_param=t.test.light(Y)
mean(p.values<.05)
mean(p.values_param<.05)

plot.ecdf(p.values);plot.ecdf(p.values_param,add=TRUE,col=3);abline(0,1,col=2)
```

## An alternative approach

It generalizes the repeated measures approach to ubalanced designs. it is more model-based, it is less robust.


- Kherad-Pajouh, S., & Renaud, O. (2015). A general permutation approach
for analyzing repeated measures ANOVA and mixed-model designs. Statistical Papers, 56(4), 947-967.  
- Frossard, J. (2019). Permutation tests and multiple comparisons in the
linear models and mixed linear models, with extension to experiments
using electroencephalography. DOI:
10.13097/archive-ouverte/unige:125617.  
- Frossard, J. & O. Renaud (2018). Permuco: Permutation Tests for
Regression, (Repeated Measures) ANOVA/ANCOVA and Comparison of Signals. R Packages.



## Remarks

None of the two approaches above allow to deal with crossed random effects (e.g. subjects and stimuli). The problem is neglected in practice, while it is of vital importance. I'm working on it (with limited and frustrating results).



# Testing with Covariates (confounders)

## Linear model

Based on my favorite approach:  

- [(theory) pdf ](https://github.com/livioivil/inference_basics/blob/master/perm_covariates_22.pdf)  
- [(a Lab) html](https://htmlpreview.github.io/?https://github.com/livioivil/inference_basics/blob/master/perm_covariates_Lab.html)  
- [(a Lab) Rmd](https://github.com/livioivil/inference_basics/blob/master/perm_covariates_Lab.Rmd)  


- (A nice review of the regression model within the permutation framework)   
 Anderson M. Winkler, Gerard R. Ridgway, Matthew A. Webster, Stephen M. Smith, Thomas E. Nichols (2014)
Permutation inference for the general linear model, NeuroImage, Volume 92, Pages 381-397, ISSN 1053-8119 <https://doi.org/10.1016/j.neuroimage.2014.01.060>

## `flipscores`: A flexible and robust approach to General Linear Model

-    Hemerik, Goeman and Finos (2020) Robust testing in generalized linear models by sign flipping score contributions. Journal of the Royal Statistical Society Series B (Statistical Methodology) 82(3). DOI: 10.1111/rssb.12369  

- [Some slides to present the method](https://github.com/livioivil/livioivil.github.io/blob/master/talks/flipscores.pdf)  

Implemented in R package `flipscores`:  
<https://cran.r-project.org/web/packages/flipscores/index.html>  
better to use the github developer version:  
<https://github.com/livioivil/flipscores>


### we are developping extension to:  
- Inference for multiverse Analysis: PIMA (joint work with P. Girardi, A. Vesely and all the psicostat dpss core team)  
- multivariate responses (joint work with R. De Santis, S. Davenport, J. Goeman)  
- Survival Models (joint work with R. De Santis, H. Putter, J. Goeman)
- Mixed effect models (joint work with A. Andreella)
- confidence interval (any volunteer?)


# Multivariate (here specially fMRI and EEG kind of data)

- Nichols \& Holmes (2001) Nonparametric Permutation Tests For Functional Neuroimaging: A Primer with Examples. *Human Brain Mapping* 15, 1-25.
<https://onlinelibrary.wiley.com/doi/ftr/10.1002/hbm.1058>

- Se volete vedere un tutorial in R di Angela Andreella :
<https://angeella.github.io/Tutorials/pARIEEG.html>
nel tutorial tra l'altro lei presenta un suo lavoro con il quale
supera la cluster-level analysis (Lower confidence bound of the true discovery proportion):
A Andreella, J Hemerik, L Finos, W Weeda, J Goeman (2023) Permutation‐based true discovery proportions for functional magnetic resonance imaging cluster analysis. Statistics in Medicine
